language: php
php:
  - 5.3
  - 5.4
  - 5.5
  
before_script:
  - mysql -e 'create database myapp_test;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
