language: php
php:
  - 5.4
  - 5.5

env:
  - DB=mysql

addons:
  mariadb: '10.0'

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS db_test;" -uroot; fi

script: phpunit
