site_name: GeniXCMS
use_directory_urls: true
pages:
- ['index.md', 'Home']
- ['about.md', 'About']
- ['license.md', 'License']
- ['user-guide/installation.md', 'User Guide', 'Installation']
- ['user-guide/dashboard.md', 'User Guide', 'Dashboard']
- ['user-guide/configuration.md', 'User Guide', 'Configuration']
- ['user-guide/posts.md', 'User Guide', 'Posts']
- ['user-guide/category.md', 'User Guide', 'Categories']
- ['user-guide/pages.md', 'User Guide', 'Pages']
- ['user-guide/users.md', 'User Guide', 'Users']
- ['user-guide/menus.md', 'User Guide', 'Menus']
- ['api/categories.class.md', 'API', 'Categories Class']
- ['api/control.class.md', 'API', 'Control Class']
- ['api/date.class.md', 'API', 'Date Class']
- ['api/db.class.md', 'API', 'Db Class']
- ['api/gxmain.class.md', 'API', 'GxMain Class']
- ['api/image.class.md', 'API', 'Image Class']
- ['api/install.class.md', 'API', 'Install Class']
- ['api/mail.class.md', 'API', 'Mail Class']
- ['api/menus.class.md', 'API', 'Menus Class']
- ['api/mod.class.md', 'API', 'Mod Class']
- ['api/options.class.md', 'API', 'Options Class']
- ['api/paging.class.md', 'API', 'Paging Class']
- ['api/pinger.class.md', 'API', 'Pinger Class']
- ['api/posts.class.md', 'API', 'Posts Class']
- ['api/rss.class.md', 'API', 'Rss Class']
- ['api/session.class.md', 'API', 'Session Class']
- ['api/site.class.md', 'API', 'Site Class']
- ['api/sitemap.class.md', 'API', 'Sitemap Class']
- ['api/stats.class.md', 'API', 'Stats Class']
- ['api/system.class.md', 'API', 'System Class']
- ['api/theme.class.md', 'API', 'Theme Class']
- ['api/typo.class.md', 'API', 'Typo Class']
- ['api/upload.class.md', 'API', 'Upload Class']
- ['api/url.class.md', 'API', 'Url Class']
- ['api/user.class.md', 'API', 'User Class']

